### ISSUE TITLE
Technical attributes are visible on product pages by default

### ISSUE THREAD

**Issue by BrentRobert** [mollie/magento2-subscriptions#20]
**Describe the bug**
The technical attributes used on the product for the subscription are visible on the page by default.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.5-p1
- *Open source/Enterprise/B2b*: OpenSource
- *Mollie version number (Check configuration)*: Recurring 1.4.0

**To Reproduce**
Create a recurring product
Go to product page

**Expected behavior**
I don't see technical attributes for the subscription as a customer

**Actual behavior**
I see technical attributes for the subscription as a customer

**Screenshots**
![Screenshot 2022-10-14 at 13 38 22](https://user-images.githubusercontent.com/6866325/195837991-74668ef5-0f40-4c8a-901b-c7806707b346.png)

**Comment by Frank-Magmodules** [comment]
HI @BrentRobert ,

Thank you for opening this issue, we are going to fix this in our next release but for now, you can just easily hide it by setting the `Storefront Properties` option of `Visible on Catalog Pages` on the attribute configuration section to `No`.

_We will follow up on this issue once the release with the fix is here._
