### ISSUE TITLE
Shipping and billing address from initial order are not used

### ISSUE THREAD

**Issue by ThomasNegeli** [mollie/magento2-subscriptions#61]
When a subscription order is created, default shipping and billing addresses are used.
See the following 2 points in the code
https://github.com/mollie/magento2-subscriptions/blob/065ec02ac963aacfbf9b03ef3a52f97dfa50413b/Controller/Api/Webhook.php#L277
https://github.com/mollie/magento2-subscriptions/blob/065ec02ac963aacfbf9b03ef3a52f97dfa50413b/Controller/Api/Webhook.php#L215
When the customer uses multiple addresses, this might produce wrong results.
Because the customer can only configure a subscription when doing a fresh checkout, you should always use the addresses from the initial order.

**Comment by Frank-Magmodules** [comment]
Hi there @ThomasNegeli Thanks for opening this issue. In our latest release, we have addressed this issue. Newly placed subscriptions will use the address used in the order instead of defaulting to the default shipping & billing addresses. I will be closing this issue, but please don't hesitate to reopen it if necessary.
